spring:
  mail:
    host: smtp.gmail.com
    username: your mail should be written here
    password: your password for mail sending should be written here
    port: 587
    properties:
      mail:
        smtp:
          starttls:
            enable: true
          auth: true